variables:
  FLUTTER_DOCKER_IMAGE: cirrusci/flutter:2.10.0

stages:
  - precheck
  - analyze
  - test
  - build
  - transform
  - upload
  - deploy
  - promote

commitlint:
  image:
    name: gtramontina/commitlint:8.3.5
    entrypoint: [ "" ]
  stage: precheck
  needs: [ ]
  script:
    - commitlint --from origin/master --verbose
  except:
    - master

stylelint:
  image: $FLUTTER_DOCKER_IMAGE
  stage: precheck
  needs: [ ]
  script:
    - flutter format --line-length 120 --dry-run --set-exit-if-changed .

analyze:
  image: $FLUTTER_DOCKER_IMAGE
  stage: analyze
  needs: [ ]
  script:
    - flutter analyze

test:
  image: $FLUTTER_DOCKER_IMAGE
  stage: test
  needs: [ ]
  before_script:
    - apt-get update
    - apt-get install -y libsqlite3-dev
  script:
    - flutter test --coverage
  after_script:
    - lcov --remove coverage/lcov.info lib/database.drift.dart --output-file coverage/lcov.info
    - genhtml --output ./coverage coverage/lcov.info
  coverage: '/^\s+lines\.+:\s+([\d.]+\%)\s+/'

build:appbundle:debug:
  image: $FLUTTER_DOCKER_IMAGE
  stage: build
  needs: [ ]
  except:
    - master
    - tags
  script:
    - flutter build appbundle --debug

build:appbundle:release:
  image: $FLUTTER_DOCKER_IMAGE
  stage: build
  needs: [ ]
  only:
    - master
    - tags
  before_script:
    - echo "$GOOGLE_SERVICES_JSON" > android/app/google-services.json
    - echo -n "$SIGNING_JKS_FILE_BASE64" | base64 -d > android/app/upload-keystore.jks
    - if [ -n "$CI_COMMIT_TAG" ]; then BUILD_NAME=$CI_COMMIT_TAG; else BUILD_NAME=$CI_COMMIT_SHORT_SHA; fi
  script:
    - flutter build appbundle --release --build-number=$CI_PIPELINE_IID --build-name=$BUILD_NAME
  artifacts:
    paths:
      - build/app/outputs/bundle/release/app-release.aab

build:apk:
  image: openjdk:16-buster
  stage: transform
  needs: [ "build:appbundle:release" ]
  only:
    - tags
  before_script:
    - echo -n "$SIGNING_JKS_FILE_BASE64" | base64 -d > android/app/upload-keystore.jks
    - wget https://github.com/google/bundletool/releases/download/1.6.1/bundletool-all-1.6.1.jar -O bundletool.jar
  script:
    - java -jar bundletool.jar build-apks --mode=universal --bundle=build/app/outputs/bundle/release/app-release.aab --output=app-release.apks --ks=android/app/upload-keystore.jks --ks-pass=pass:$SIGNING_KEYSTORE_PASSWORD --ks-key-alias=$SIGNING_KEY_ALIAS --key-pass=pass:$SIGNING_KEY_PASSWORD
    - unzip app-release.apks
    - mv universal.apk app-release.apk
  artifacts:
    paths:
      - app-release.apk

deploy:gitlab-release:
  image: curlimages/curl:latest
  stage: deploy
  needs: [ "commitlint", "stylelint", "analyze", "test", "build:apk" ]
  only:
    - tags
  script:
    - 'curl --header "JOB-TOKEN: $CI_JOB_TOKEN" --upload-file app-release.apk "${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/flauncher/$CI_COMMIT_TAG/flauncher-$CI_COMMIT_TAG.apk"'

deploy:play-store:
  stage: deploy
  needs: [ "commitlint", "stylelint", "analyze", "test", "build:appbundle:release" ]
  image: ruby:2.6.3
  only:
    - tags
  before_script:
    - echo "$GOOGLE_PLAY_API_KEY" > android/fastlane/google_play_api_key.json
    - export LC_ALL=en_US.UTF-8
    - export LANG=en_US.UTF-8
    - gem install fastlane -NV
    - cd android
  script:
    - fastlane deploy

promote:play-store:
  stage: promote
  needs: [ "deploy:play-store" ]
  image: ruby:2.6.3
  when: manual
  only:
    - tags
  before_script:
    - echo "$GOOGLE_PLAY_API_KEY" > android/fastlane/google_play_api_key.json
    - export LC_ALL=en_US.UTF-8
    - export LANG=en_US.UTF-8
    - gem install fastlane -NV
    - cd android
  script:
    - fastlane promote

promote:gitlab-release:
  stage: promote
  needs: [ "deploy:gitlab-release" ]
  image: registry.gitlab.com/gitlab-org/release-cli:latest
  when: manual
  only:
    - tags
  script:
    - echo 'running promote:gitlab-release'
  release:
    name: $CI_COMMIT_TAG
    description: FLauncher v$CI_COMMIT_TAG
    tag_name: $CI_COMMIT_TAG
    assets:
      links:
        - name: flauncher-$CI_COMMIT_TAG.apk
          url: ${CI_API_V4_URL}/projects/${CI_PROJECT_ID}/packages/generic/flauncher/$CI_COMMIT_TAG/flauncher-$CI_COMMIT_TAG.apk
          filepath: /flauncher-$CI_COMMIT_TAG.apk
